class EmailCampaignData {
  final int? id; // Make this nullable if it's generated by the database
  final String subject;
  final String previewText;
  final String fromName;
  final String fromEmail;

  EmailCampaignData({
    this.id,
    required this.subject,
    required this.previewText,
    required this.fromName,
    required this.fromEmail,
  });

  // CopyWith method to create a new instance with modified fields
  EmailCampaignData copyWith({
    int? id,
    String? subject,
    String? previewText,
    String? fromName,
    String? fromEmail,
  }) {
    return EmailCampaignData(
      id: id ?? this.id,
      subject: subject ?? this.subject,
      previewText: previewText ?? this.previewText,
      fromName: fromName ?? this.fromName,
      fromEmail: fromEmail ?? this.fromEmail,
    );
  }
}
